name: teaching_ai
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.2
  just_audio: ^0.9.42
  audioplayers: ^6.5.0
  webview_flutter: ^4.4.2
  flutter_svg: ^2.0.7
  firebase_core: ^3.6.0
  cloud_firestore: ^5.1.0
  firebase_auth: ^5.1.0
  speech_to_text: ^7.3.0
  font_awesome_flutter: ^10.7.0
  google_fonts: ^6.2.1
  flutter_markdown: ^0.6.18
  firebase_analytics: ^11.6.0
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/

  fonts:
    - family: NotoSans
      fonts:
        - asset: assets/fonts/NotoSans-Regular.ttf
        - asset: assets/fonts/NotoSans-Bold.ttf
          weight: 700
