// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_methods
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAodq9Rd1qVeJ_5tXlvXuVB1ft8-Tocbew',
    appId: '1:383985445628:web:88598cb7bfdae20c068579',
    messagingSenderId: '383985445628',
    projectId: 'lingua-8e3dc',
    authDomain: 'lingua-8e3dc.firebaseapp.com',
    storageBucket: 'lingua-8e3dc.firebasestorage.app',
    measurementId: 'G-MEASUREMENT_ID',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAodq9Rd1qVeJ_5tXlvXuVB1ft8-Tocbew',
    appId: '1:383985445628:android:88598cb7bfdae20c068579',
    messagingSenderId: '383985445628',
    projectId: 'lingua-8e3dc',
    storageBucket: 'lingua-8e3dc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAodq9Rd1qVeJ_5tXlvXuVB1ft8-Tocbew',
    appId: '1:383985445628:ios:rag66h4ap76e32vi83m0nka0knevt6l4',
    messagingSenderId: '383985445628',
    projectId: 'lingua-8e3dc',
    storageBucket: 'lingua-8e3dc.firebasestorage.app',
    iosBundleId: 'com.equilib.otolingo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAodq9Rd1qVeJ_5tXlvXuVB1ft8-Tocbew',
    appId: '1:383985445628:ios:rag66h4ap76e32vi83m0nka0knevt6l4',
    messagingSenderId: '383985445628',
    projectId: 'lingua-8e3dc',
    storageBucket: 'lingua-8e3dc.firebasestorage.app',
    iosBundleId: 'com.equilib.otolingo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAodq9Rd1qVeJ_5tXlvXuVB1ft8-Tocbew',
    appId: '1:383985445628:web:88598cb7bfdae20c068579',
    messagingSenderId: '383985445628',
    projectId: 'lingua-8e3dc',
    authDomain: 'lingua-8e3dc.firebaseapp.com',
    storageBucket: 'lingua-8e3dc.firebasestorage.app',
    measurementId: 'G-MEASUREMENT_ID',
  );

}
